# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemoMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_method_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('q_item', models.CharField(max_length=50)),
                ('q_index', models.CharField(max_length=200)),
                ('q_explanation', models.CharField(max_length=200)),
                ('q_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pages.DemoCategory')),
                ('q_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='pages.DemoMethod')),
            ],
        ),
        migrations.CreateModel(
            name='DemoStarLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_star_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_status_name', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='q_star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_level', to='pages.DemoStarLevel'),
        ),
    ]
