# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20170504_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcontent',
            old_name='category_content',
            new_name='web_category_content',
        ),
        migrations.RenameField(
            model_name='webcontent',
            old_name='category_name',
            new_name='web_category_name',
        ),
    ]
